version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs:/var/log/nginx/
        depends_on:
            - php
            - mysql

    mysql:
        image: mysql:5.7.22
        container_name : mysql
        ports:
            - "3307:3306"

        volumes:
            - ./mysqldata:/var/lib/mysql

        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "secret"
            MYSQL_DATABASE: "auth_test_db"

    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        logging:
            driver: "none"
        ports:
            - "9000:9000"
